{% set name = "qsimcirq" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumlib/qsim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 81101fe9e6356e54125f703956e787aa366717c1e6e77aea794879b53c84ff60
  patches:
    - patches/0001-Fix-no-instance-of-constructor-qsim-StateSpaceCUDA-F.patch  # [cuda_compiler_version != "None"]
    - patches/0002-Remove-PUBLIC-from-target_link_libraries-with-OpenMP.patch  # [cuda_compiler_version != "None"]
    - patches/0003-Set-pybind11_INCLUDE_DIRS-correctly-for-CUDA.patch          # [cuda_compiler_version != "None"]
    - patches/0004-Set-PYTHON_INCLUDE_DIR-in-setup.py.patch
    - patches/0005-Allow-installing-for-Python-3.12.patch
    - patches/0006-Set-CUDA_ARCHITECTURES-all-cmake-policy-CMP0104.patch       # [cuda_compiler_version != "None"]
    - patches/0007-Always-skip-test_cirq_qsim_gpu_amplitudes-because-no.patch  # [cuda_compiler_version != "None"]
    - patches/0008-Add-support-for-additional-CMake-arguments.patch
    - patches/0009-Use-CMAKE_SYSTEM_NAME-and-CMAKE_SYSTEM_PROCESSOR-for.patch
    - patches/0010-Do-not-set-includes-on-Apple-arm64-in-basis.patch

build:
  skip: true  # [win]
  # For some reason Python 3.12 fails to resolve and gives:
  # nothing provides _python_rc needed by python-3.12.0rc3-rc3_hab00c5b_1_cpython
  skip: true  # [cuda_compiler_version != "None" and py==312]
  number: 5
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                 # [cuda_compiler_version == "None"]
  script_env:
    - CUQUANTUM_ROOT=$PREFIX  # [cuda_compiler_version != "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - pybind11-abi
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - openmpi
    - cmake >=3.27
    - make
  host:
    - python
    - pybind11
    - setuptools >=45
    - wheel
    - pip
    - numpy
    - llvm-openmp  # [osx]
    - cuquantum-python   # [cuda_compiler_version != "None"]
    - custatevec         # [cuda_compiler_version != "None"]
    - libcublas-dev      # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - absl-py
    - cirq-core
    - pybind11
    - typing_extensions
    - {{ pin_compatible('numpy') }}
    - cuquantum-python  # [cuda_compiler_version != "None"]
    - custatevec        # [cuda_compiler_version != "None"]
    - __cuda            # [cuda_compiler_version != "None"]

test:
  imports:
    - qsimcirq
  source_files:
    - qsimcirq_tests
  commands:
    # With CUDA `pip check` fails with:
    # cuquantum-python-cu11 23.10.0 requires custatevec-cu11, which is not installed.
    - pip check  # [cuda_compiler_version == "None"]
    - cd qsimcirq_tests && pytest -vvv .
  requires:
    - pip
    - pytest

about:
  home: https://quantumai.google/qsim
  summary: Quantum circuit simulators qsim and qsimh.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - BastianZim
